x = input('Digite algo: ')
print(f'É um título?  {x.istitle()}')
print(f'É um caractere ASCII?  {x.isascii()}')
print(f'É um caracter decimal?  {x.isdecimal()}')
print(f'Só tem espaços? {x.isspace()}')
print(f'É uma sequência de números? {x.isdigit()}')
print(f'É um identificador válido? {x.isidentifier()}')
print(f'É um caractere imprimível? {x.isprintable()}')
print(f'É numérico? {x.isnumeric()}')
print(f'É alfabético? {x.isalpha()}')
print(f'É alfanumérico? {x.isalnum()}')
print(f'Todas letras maiúsculas? {x.isupper()}')
print(f'Todas letras minúsculas? {x.islower()}')

